---

lxd_preseed:
  config: "{{lxd_daemon_config}}"
  cluster:
    enabled: true
  #storage_pools: "{{lxd_storage_pools_config}}"
  #networks: "{{lxd_networks_config}}"
  #profiles: "{{lxd_profiles_config}}"

lxd_daemon_config:
  core.https_address: "{{lxd_core_https_address}}"
  images.auto_update_interval: 6

lxd_cluster_bootstrap_config:
  enabled: true
  server_name: "{{lxd_cluster_server_name}}"

lxd_cluster_join_config:
  enabled: true
  server_address: "{{lxd_cluster_server_address}}"
  cluster_token: "{{lxd_cluster_token}}"

lxd_cluster_token: "{{lxd_cluster_join_token_task.stdout_lines[1]}}"
