---


lxd_preseed:
  config: "{{lxd_daemon_config}}"
  cluster:
    enabled: true
  storage_pools: "{{lxd_storage_pools_config}}"
  networks: "{{lxd_networks_config}}"
  profiles: "{{lxd_profiles_config}}"

lxd_daemon_config:
  core.https_address: "{{lxd_core_https_address}}"
  images.auto_update_interval: 6

lxd_cluster_bootstrap_config:
  enabled: true
  server_name: "{{lxd_cluster_server_name}}"

lxd_cluster_join_config:
  enabled: true
  server_address: "{{lxd_cluster_server_address}}"
  cluster_token: "{{lxd_cluster_token}}"

lxd_cluster_token: "{{lxd_cluster_join_token_task.stdout_lines[1]}}"

lxd_storage_pools_config:
- name: default
  description: default storage pool
  driver: "{{ lxd_default_storage_pool_driver }}"

lxd_networks_config:
- name: lxdbr0
  description: default lxd bridge
  type: bridge
  config:
    ipv4.address: "{{lxd_ipv4_address|default('auto')}}"
    ipv4.nat: "{{ lxd_ipv4_nat }}"
    ipv6.address: "{{lxd_ipv6_address|default('auto')}}"
    ipv6.nat: "{{ lxd_ipv6_nat }}"

lxd_profiles_config:
- name: default
  description: default profile
  config:
    limits.cpu: 1
    limits.memory: 1GB
  devices:
    eth0:
      name: eth0
      network: lxdbr0
      type: nic
    root:
      path: /
      pool: default
      type: disk
