---
  
- name: write ssh_known_hosts file
  local_action: known_hosts
  args:
    path: "{{ playbook_dir }}/ssh_known_hosts"
    name: "{{ item }}"
    key: "{{ item }},{{ hostvars[item].ssh_ip }} ssh-ed25519 {{ hostvars[item].ssh_host_key_ed25519_public }}"
  with_items: "{{play_hosts}}"
  run_once: true
