---

- name: delete ssh host keys
  file:
    path: "{{item}}"
    state: absent
  with_fileglob:
    - /etc/ssh/ssh_host_*
  register: _ssh_host_keys_delete

- name: reconfigure ssh server
  shell: dpkg-reconfigure openssh-server
