---

- name: host_vars directory
  local_action: file path=host_vars/{{inventory_hostname}} state=directory

- name: host_vars file
  local_action: template src=host_vars.j2 dest=host_vars/{{inventory_hostname}}/ssh_host_key.yml

- name: write ssh_known_hosts file
  local_action: known_hosts
  args:
    path: "{{ playbook_dir }}/ssh_known_hosts"
    name: "{{ inventory_hostname }}"
    key: "{{ inventory_hostname }},{{ ssh_ip }} {{ _ssh_key_type[ssh_host_key_type] }} {{ _ssh_host_key[ssh_host_key_type] }}"
