---

- name: host_vars directory
  local_action: file
  args:
    path: "{{inventory_dir}}/host_vars/{{inventory_hostname}}"
    state: directory

- name: host_vars file
  local_action: template
  args:
    src: host_vars.j2
    dest: "{{inventory_dir}}/host_vars/{{inventory_hostname}}/ssh_host_key.yaml"
