---

- name: set additional logical volumes
  set_fact:
    logical_volumes: "{{lookup('template','logical_volumes.json.j2')}}"
    filesystems: "{{lookup('template','logical_volume_filesystems.json.j2')}}"
  when: partitioning_profile_volumes is defined
