mdraid_devices: []

boot_device: "{{ hard_disks | json_query(\"[].partitions[?usage=='boot'][].device\") | first }}"
rescue_device: "{{ hard_disks | json_query(\"[].partitions[?usage=='rescue'][].device\") | first }}"
data_device: "{{ hard_disks | json_query(\"[].partitions[?usage=='data'][].device\") | first }}"

debian_boot_packages: []
