---

- hosts: all
  become: true
  tasks:
  - name: update debian cache and upgrade packages
    apt:
      update_cache: true
      upgrade: full
  - name: debian packages
    apt:
      pkg:
      - kitty-terminfo
  
- import_playbook: lxd_servers.yaml

- hosts: lxd_servers
  become: true
  gather_facts: false
  tasks:
  - name: add vagrant user to lxd group
    user:
      name: vagrant
      groups:
      - lxd
