---

- import_tasks: setup.yaml

- name: Gathering Facts again after adding lxd info fact
  setup:

- when: ansible_local.lxd_info.environment.server_clustered
  name: Add all clustered lxd servers to a group
  ansible.builtin.group_by:
    key: lxd_clustered_servers

- when:
  - lxd_cluster_bootstrap
  - not 'lxd_clustered_servers' in groups
  - not ansible_local.lxd_info.environment.server_clustered
  run_once: true
  name: lxd bootstrap cluster
  command: lxd init --preseed
  args:
    stdin: "{{lxd_preseed|combine({'cluster':lxd_cluster_bootstrap_config})}}"

- name: Gathering Facts again after lxd bootstraping
  setup:

- when: ansible_local.lxd_info.environment.server_clustered
  name: Add all clustered lxd servers to a group
  ansible.builtin.group_by:
    key: lxd_clustered_servers

- when: not ansible_local.lxd_info.environment.server_clustered
  block:

  - name: get lxd cluster join token
    command: 
      argv:
      - lxc 
      - cluster
      - add
      - "{{lxd_cluster_server_name}}"
    delegate_to: "{{groups.lxd_clustered_servers|first}}"
    register: lxd_cluster_join_token_task

  - name: assert that we got a token
    assert:
      that: "'join token' in lxd_cluster_join_token_task.stdout_lines[0]"

  # - debug:
  #     msg: 
  #       lxd_cluster_token: "{{lxd_cluster_token}}"

  - name: lxd join cluster
    command: lxd init --preseed
    args:
      stdin: "{{lxd_preseed|combine({'cluster':lxd_cluster_join_config})}}"

# - name: lxd init
#   command: lxd init --preseed
#   args:
#     stdin: "{{lxd_preseed}}"
