label_type: msdos

partitions:
  - type: primary
    start: 512MiB
    end: 1GiB
    usage: boot
  - type: primary
    start: 1GiB
    end: 2GiB
    usage: rescue
  - type: primary
    start: 2GiB
    end: "{{last_partition_end}}"
    usage: data

debian_boot_packages:
  - grub-pc

grub_bootloader_target: i386-pc
